name: Create new release

on:
  release:
    types: [created]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 14
      run: sudo xcode-select --switch /Applications/Xcode_14.1.app
    - name: Test
      run: make tests

  release:
    needs: [test]
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 14
      run: sudo xcode-select --switch /Applications/Xcode_14.1.app
    - name: Build and upload XCFrameworks, recreate tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make version=${{ github.event.release.tag_name }} github
