name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string

permissions:
  contents: read

env:
  XCODE_VERSION: Xcode_26.1

jobs:
  test:
    name: ${{ env.XCODE_VERSION }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["macOS", "iOSsim", "tvOSsim", "watchOSsim", "visionOSsim"]
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup ${{ env.XCODE_VERSION }}
      id: xcode
      uses: ./.github/actions/setup-xcode
      with:
        version: ${{ env.XCODE_VERSION }}
    - name: Test
      run: >-
        make XC_LOG=tests
        IOS_SIMULATOR="${{ steps.xcode.outputs.ios-simulator }}"
        TVOS_SIMULATOR="${{ steps.xcode.outputs.tvos-simulator }}"
        WATCHOS_SIMULATOR="${{ steps.xcode.outputs.watchos-simulator }}"
        VISIONOS_SIMULATOR="${{ steps.xcode.outputs.visionos-simulator }}"
        tests/unit/${{ matrix.platform }}
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ env.XCODE_VERSION }}-${{ matrix.platform }}-tests-logs
        path: "*-tests.log"

  release:
    name: Publish Release
    needs: [test]
    runs-on: macos-26
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Get GitHub token via dd-octo-sts
      uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
      id: octo-sts
      with:
        scope: DataDog/dd-sdk-swift-testing
        policy: self.github.create-release.workflow-dispatch
    - name: Setup ${{ env.XCODE_VERSION }}
      uses: ./.github/actions/setup-xcode
      with:
        version: ${{ env.XCODE_VERSION }}
    - name: Fix git repo url with obtained token
      env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
    - name: Build and upload XCFrameworks, create draft release
      env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: make XC_LOG=archive version=${{ github.event.inputs.version }} github_release
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: xcode-archive-logs
        path: "*-archive.log"
  
  publish-pod:
    name: Publish Pod
    needs: [release]
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: "${{ github.event.inputs.version }}"
    - name: Publish
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: make publish_pod
