name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Select Xcode 26.0
      run: sudo xcode-select --switch /Applications/Xcode_26.0.app
    - name: Test
      run: make XC_LOG=tests IOS_SIMULATOR="iPhone 17" TVOS_SIMULATOR="Apple TV" tests
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: xcode-tests-logs
        path: "*-tests.log"

  release:
    name: Publish Release
    needs: [test]
    runs-on: macos-26
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Get GitHub token via dd-octo-sts
      uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
      id: octo-sts
      with:
        scope: DataDog/dd-sdk-swift-testing
        policy: self.github.create-release.workflow-dispatch
    - name: Select Xcode 26.0
      run: sudo xcode-select --switch /Applications/Xcode_26.0.app
    - name: Print git remote info
      run: git remote -v
    - name: Build and upload XCFrameworks, create draft release
      env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
	GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: make XC_LOG=archive version=${{ github.event.inputs.version }} github_release
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: xcode-archive-logs
        path: "*-archive.log"
  
  publish-pod:
    name: Publish Pod
    needs: [release]
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        ref: "${{ github.event.inputs.version }}"
    - name: Publish
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: make publish_pod
