name: Create new release

on:
  release:
    types: [created]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 14
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - name: Test
      run: make XC_LOG=tests tests
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: xcode-tests-logs
        path: "*-tests.log"

  release:
    needs: [test]
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 14
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - name: Build and upload XCFrameworks, recreate tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: make XC_LOG=archive version=${{ github.event.release.tag_name }} github
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: xcode-archive-logs
        path: "*-archive.log"
