name: Create new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.4
      run: sudo xcode-select --switch /Applications/Xcode_16.4.app
    - name: Test
      run: make XC_LOG=tests tests
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: xcode-tests-logs
        path: "*-tests.log"

  release:
    needs: [test]
    runs-on: macos-15
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.4
      run: sudo xcode-select --switch /Applications/Xcode_16.4.app
    - name: Build and upload XCFrameworks, recreate tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make XC_LOG=archive version=${{ github.event.inputs.version }} github_release
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v4
      with:
        name: xcode-archive-logs
        path: "*-archive.log"
