name: Create relase

on:
  release:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run Tests
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 13.3.1
      run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
    - name: Test
      run: make tests

  release:
    needs: [test]
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 13.3.1
      run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
    - name: Build XCFrameworks
      run: make release
    - name: Get the tag version
      id: tag_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Update swift binary and recreate tag
      run: sh Scripts/uploadBinary.sh $GITHUB_TOKEN ${{ steps.tag_version.outputs.VERSION }} ${{ steps.branch-name.outputs.current_branch }}


