name: Integration Tests

on:
  schedule:
  - cron: 0 2 * * 1-5
  workflow_dispatch:

jobs:
  unit:
    name: Unit Tests
    uses: ./.github/workflows/unitTests.yml

  integration:
    name: ${{ matrix.xcode }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ["Xcode_26.2", "Xcode_26.4"]
        platform: ["macOS", "iOSsim", "tvOSsim", "watchOSsim", "visionOSsim"]
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup ${{ matrix.xcode }}
      id: xcode
      uses: ./.github/actions/setup-xcode
      with:
        version: ${{ matrix.xcode }}
    - name: Run tests for ${{ matrix.platform }}
      run: >-
        make XC_LOG=integration
        IOS_SIMULATOR="${{ steps.xcode.outputs.ios-simulator }}"
        TVOS_SIMULATOR="${{ steps.xcode.outputs.tvos-simulator }}"
        WATCHOS_SIMULATOR="${{ steps.xcode.outputs.watchos-simulator }}"
        VISIONOS_SIMULATOR="${{ steps.xcode.outputs.visionos-simulator }}"
        tests/integration/${{ matrix.platform }}
      env:
        DD_API_KEY: '${{ secrets.DD_API_KEY }}'
        DD_TEST_RUNNER: 1
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ matrix.xcode }}-${{ matrix.platform }}-integration-log
        path: "logs-integration/*.log"
