name: Publish to CocoaPods

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-pod:
    name: Publish Pod
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: make publish_pod
