name: Unit Tests

on:
  pull_request:
    branches-ignore:
      - 'release-*'
      - 'release/*'
  workflow_dispatch:
  workflow_call:

jobs:
  unit:
    name: ${{ matrix.xcode }} / ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ["Xcode_26.1", "Xcode_26.2", "Xcode_26.4"]
        platform: ["macOS", "iOSsim", "tvOSsim", "watchOSsim", "visionOSsim"]
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup ${{ matrix.xcode }}
      id: xcode
      uses: ./.github/actions/setup-xcode
      with:
        version: ${{ matrix.xcode }}
    - name: Unit tests
      run: >-
        make XC_LOG=unit
        IOS_SIMULATOR="${{ steps.xcode.outputs.ios-simulator }}"
        TVOS_SIMULATOR="${{ steps.xcode.outputs.tvos-simulator }}"
        WATCHOS_SIMULATOR="${{ steps.xcode.outputs.watchos-simulator }}"
        VISIONOS_SIMULATOR="${{ steps.xcode.outputs.visionos-simulator }}"
        tests/unit/${{ matrix.platform }}
    - name: Attach Xcode logs
      if: '!cancelled()'
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ matrix.xcode }}-${{ matrix.platform }}-unit-logs
        path: "*-unit.log"
